# CafecaBackend Default Config

title = "CafecaBackend"

[base]
folder = "MerMer-framework"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /api/questions | Bot.FindCafeca.getQuestions",
  "get | /api/suggestion | Bot.FindCafeca.getSuggestion",
  "get | /api/store/:storeID | Bot.FindCafeca.getStore",
  "get | /policy/* | Static.Utils.readPackageInfo"
]